# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Novis Obliviate' do
    	pod 'Alamofire', '~> 4.0'
	pod 'Zip', '~> 0.6'
end

target 'Novis ObliviateTests' do

end

target 'Novis ObliviateUITests' do

end

